name: Sync Worker Snapshot

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch snapshot from worker
        env:
          WORKER_BASE_URL: ${{ secrets.WORKER_BASE_URL }}
        run: |
          if [ -z "$WORKER_BASE_URL" ]; then
            echo "Missing WORKER_BASE_URL secret" >&2
            exit 1
          fi
          mkdir -p workers
          curl -sSfL "$WORKER_BASE_URL/api/sync/snapshot" | jq '.' > workers/hiscores-snapshot.json

      - name: Commit snapshot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync worker snapshot"
          file_pattern: workers/hiscores-snapshot.json
